// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: ESP32TPMS

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Top;
lv_obj_t * ui_Top_Container;
lv_obj_t * ui_Top_Info_Row;
lv_obj_t * ui_Front_Label;
lv_obj_t * ui_Front_Battery_Value;
lv_obj_t * ui_Back_Label;
lv_obj_t * ui_Back_Battery_Value;
lv_obj_t * ui_Pressure_Data_Row;
lv_obj_t * ui_Front_Pressure;
lv_obj_t * ui_Front_Pressure_Value;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Front_Data_Spacer;
lv_obj_t * ui_Back_Pressure;
lv_obj_t * ui_Back_Pressure_Value;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Bottom;
lv_obj_t * ui_Bottom_Container;
lv_obj_t * ui_Temperature_Data_Row;
lv_obj_t * ui_Front_Temperature;
lv_obj_t * ui_Front_Temperature_Value;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Back_Data_Spacer;
lv_obj_t * ui_Back_Temperature;
lv_obj_t * ui_Back_Temperature_Value;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Bottom_Row;
lv_obj_t * ui_Timer_Label;
lv_obj_t * ui_Timer;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
