// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ESP32TPMS

#ifndef _ESP32TPMS_UI_H
#define _ESP32TPMS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Top;
extern lv_obj_t * ui_Top_Container;
extern lv_obj_t * ui_Top_Info_Row;
extern lv_obj_t * ui_Front_Label;
extern lv_obj_t * ui_Front_Battery_Value;
extern lv_obj_t * ui_Back_Label;
extern lv_obj_t * ui_Back_Battery_Value;
extern lv_obj_t * ui_Pressure_Data_Row;
extern lv_obj_t * ui_Front_Pressure;
extern lv_obj_t * ui_Front_Pressure_Value;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Front_Data_Spacer;
extern lv_obj_t * ui_Back_Pressure;
extern lv_obj_t * ui_Back_Pressure_Value;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Bottom;
extern lv_obj_t * ui_Bottom_Container;
extern lv_obj_t * ui_Temperature_Data_Row;
extern lv_obj_t * ui_Front_Temperature;
extern lv_obj_t * ui_Front_Temperature_Value;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Back_Data_Spacer;
extern lv_obj_t * ui_Back_Temperature;
extern lv_obj_t * ui_Back_Temperature_Value;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Bottom_Row;
extern lv_obj_t * ui_Timer_Label;
extern lv_obj_t * ui_Timer;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
