// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ESP32TPMS

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Top = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Top);
    lv_obj_set_width(ui_Top, 214);
    lv_obj_set_height(ui_Top, 90);
    lv_obj_set_x(ui_Top, 0);
    lv_obj_set_y(ui_Top, -45);
    lv_obj_set_align(ui_Top, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Top, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Top_Container = lv_obj_create(ui_Top);
    lv_obj_remove_style_all(ui_Top_Container);
    lv_obj_set_width(ui_Top_Container, 231);
    lv_obj_set_height(ui_Top_Container, 93);
    lv_obj_set_x(ui_Top_Container, 0);
    lv_obj_set_y(ui_Top_Container, -2);
    lv_obj_set_align(ui_Top_Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Top_Container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Top_Container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Top_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Top_Info_Row = lv_obj_create(ui_Top_Container);
    lv_obj_remove_style_all(ui_Top_Info_Row);
    lv_obj_set_width(ui_Top_Info_Row, 152);
    lv_obj_set_height(ui_Top_Info_Row, 21);
    lv_obj_set_x(ui_Top_Info_Row, 124);
    lv_obj_set_y(ui_Top_Info_Row, 59);
    lv_obj_set_align(ui_Top_Info_Row, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Top_Info_Row, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Top_Info_Row, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Top_Info_Row, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Front_Label = lv_label_create(ui_Top_Info_Row);
    lv_obj_set_width(ui_Front_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Front_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Front_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Front_Label, "F:");
    lv_obj_set_style_text_font(ui_Front_Label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Front_Battery_Value = lv_label_create(ui_Top_Info_Row);
    lv_obj_set_width(ui_Front_Battery_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Front_Battery_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Front_Battery_Value, -26);
    lv_obj_set_y(ui_Front_Battery_Value, -1);
    lv_obj_set_align(ui_Front_Battery_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Front_Battery_Value, "---%");
    lv_obj_set_style_text_font(ui_Front_Battery_Value, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Front_Battery_Value, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Front_Battery_Value, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Front_Battery_Value, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Front_Battery_Value, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_Label = lv_label_create(ui_Top_Info_Row);
    lv_obj_set_width(ui_Back_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Back_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Back_Label, "B:");
    lv_obj_set_style_text_font(ui_Back_Label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Back_Label, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Back_Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Back_Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Back_Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_Battery_Value = lv_label_create(ui_Top_Info_Row);
    lv_obj_set_width(ui_Back_Battery_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back_Battery_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Back_Battery_Value, 27);
    lv_obj_set_y(ui_Back_Battery_Value, -158);
    lv_obj_set_align(ui_Back_Battery_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Back_Battery_Value, "---%");
    lv_obj_set_style_text_font(ui_Back_Battery_Value, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pressure_Data_Row = lv_obj_create(ui_Top_Container);
    lv_obj_remove_style_all(ui_Pressure_Data_Row);
    lv_obj_set_width(ui_Pressure_Data_Row, 223);
    lv_obj_set_height(ui_Pressure_Data_Row, 70);
    lv_obj_set_x(ui_Pressure_Data_Row, -1);
    lv_obj_set_y(ui_Pressure_Data_Row, -35);
    lv_obj_set_align(ui_Pressure_Data_Row, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Pressure_Data_Row, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Pressure_Data_Row, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Pressure_Data_Row, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Front_Pressure = lv_obj_create(ui_Pressure_Data_Row);
    lv_obj_remove_style_all(ui_Front_Pressure);
    lv_obj_set_width(ui_Front_Pressure, 100);
    lv_obj_set_height(ui_Front_Pressure, 50);
    lv_obj_set_x(ui_Front_Pressure, -57);
    lv_obj_set_y(ui_Front_Pressure, -37);
    lv_obj_set_align(ui_Front_Pressure, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Front_Pressure, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Front_Pressure, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Front_Pressure, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Front_Pressure, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Front_Pressure, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Red);
    ui_object_set_themeable_style_property(ui_Front_Pressure, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Red);

    ui_Front_Pressure_Value = lv_label_create(ui_Front_Pressure);
    lv_obj_set_width(ui_Front_Pressure_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Front_Pressure_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Front_Pressure_Value, -4);
    lv_obj_set_y(ui_Front_Pressure_Value, -4);
    lv_obj_set_align(ui_Front_Pressure_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Front_Pressure_Value, "--.-");
    lv_obj_set_style_text_font(ui_Front_Pressure_Value, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Front_Pressure);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 26);
    lv_obj_set_y(ui_Label2, 18);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "psi");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Front_Data_Spacer = lv_obj_create(ui_Pressure_Data_Row);
    lv_obj_remove_style_all(ui_Front_Data_Spacer);
    lv_obj_set_width(ui_Front_Data_Spacer, 10);
    lv_obj_set_height(ui_Front_Data_Spacer, 50);
    lv_obj_set_align(ui_Front_Data_Spacer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Front_Data_Spacer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Front_Temperature = lv_obj_create(ui_Pressure_Data_Row);
    lv_obj_remove_style_all(ui_Front_Temperature);
    lv_obj_set_width(ui_Front_Temperature, 100);
    lv_obj_set_height(ui_Front_Temperature, 50);
    lv_obj_set_x(ui_Front_Temperature, -57);
    lv_obj_set_y(ui_Front_Temperature, -37);
    lv_obj_set_align(ui_Front_Temperature, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Front_Temperature, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Front_Temperature, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Front_Temperature, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Front_Temperature, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Front_Temperature, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Front_Temperature, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);

    ui_Front_Temperature_Value = lv_label_create(ui_Front_Temperature);
    lv_obj_set_width(ui_Front_Temperature_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Front_Temperature_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Front_Temperature_Value, -4);
    lv_obj_set_y(ui_Front_Temperature_Value, -4);
    lv_obj_set_align(ui_Front_Temperature_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Front_Temperature_Value, "--.-");
    lv_obj_set_style_text_font(ui_Front_Temperature_Value, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Front_Temperature);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 26);
    lv_obj_set_y(ui_Label4, 18);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "°C");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bottom = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Bottom);
    lv_obj_set_width(ui_Bottom, 214);
    lv_obj_set_height(ui_Bottom, 90);
    lv_obj_set_x(ui_Bottom, 1);
    lv_obj_set_y(ui_Bottom, 44);
    lv_obj_set_align(ui_Bottom, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Bottom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bottom_Container = lv_obj_create(ui_Bottom);
    lv_obj_remove_style_all(ui_Bottom_Container);
    lv_obj_set_width(ui_Bottom_Container, 231);
    lv_obj_set_height(ui_Bottom_Container, 93);
    lv_obj_set_x(ui_Bottom_Container, 0);
    lv_obj_set_y(ui_Bottom_Container, -2);
    lv_obj_set_align(ui_Bottom_Container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Bottom_Container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Bottom_Container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Bottom_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Temperature_Data_Row = lv_obj_create(ui_Bottom_Container);
    lv_obj_remove_style_all(ui_Temperature_Data_Row);
    lv_obj_set_width(ui_Temperature_Data_Row, 223);
    lv_obj_set_height(ui_Temperature_Data_Row, 70);
    lv_obj_set_x(ui_Temperature_Data_Row, -1);
    lv_obj_set_y(ui_Temperature_Data_Row, -35);
    lv_obj_set_align(ui_Temperature_Data_Row, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Temperature_Data_Row, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Temperature_Data_Row, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Temperature_Data_Row, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Back_Pressure = lv_obj_create(ui_Temperature_Data_Row);
    lv_obj_remove_style_all(ui_Back_Pressure);
    lv_obj_set_width(ui_Back_Pressure, 100);
    lv_obj_set_height(ui_Back_Pressure, 50);
    lv_obj_set_x(ui_Back_Pressure, -57);
    lv_obj_set_y(ui_Back_Pressure, -37);
    lv_obj_set_align(ui_Back_Pressure, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Back_Pressure, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Back_Pressure, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Back_Pressure, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Back_Pressure, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Back_Pressure, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_Back_Pressure, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Green);

    ui_Back_Pressure_Value = lv_label_create(ui_Back_Pressure);
    lv_obj_set_width(ui_Back_Pressure_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back_Pressure_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Back_Pressure_Value, -4);
    lv_obj_set_y(ui_Back_Pressure_Value, -4);
    lv_obj_set_align(ui_Back_Pressure_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Back_Pressure_Value, "--.-");
    lv_obj_set_style_text_font(ui_Back_Pressure_Value, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Back_Pressure);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 26);
    lv_obj_set_y(ui_Label1, 18);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "psi");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_Data_Spacer = lv_obj_create(ui_Temperature_Data_Row);
    lv_obj_remove_style_all(ui_Back_Data_Spacer);
    lv_obj_set_width(ui_Back_Data_Spacer, 10);
    lv_obj_set_height(ui_Back_Data_Spacer, 50);
    lv_obj_set_align(ui_Back_Data_Spacer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Back_Data_Spacer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Back_Temperature = lv_obj_create(ui_Temperature_Data_Row);
    lv_obj_remove_style_all(ui_Back_Temperature);
    lv_obj_set_width(ui_Back_Temperature, 100);
    lv_obj_set_height(ui_Back_Temperature, 50);
    lv_obj_set_x(ui_Back_Temperature, -57);
    lv_obj_set_y(ui_Back_Temperature, -37);
    lv_obj_set_align(ui_Back_Temperature, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Back_Temperature, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Back_Temperature, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Back_Temperature, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Back_Temperature, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Back_Temperature, lv_color_hex(0xBB2828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Back_Temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_Temperature_Value = lv_label_create(ui_Back_Temperature);
    lv_obj_set_width(ui_Back_Temperature_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back_Temperature_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Back_Temperature_Value, -4);
    lv_obj_set_y(ui_Back_Temperature_Value, -4);
    lv_obj_set_align(ui_Back_Temperature_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Back_Temperature_Value, "--.-");
    lv_obj_set_style_text_font(ui_Back_Temperature_Value, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Back_Temperature);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 26);
    lv_obj_set_y(ui_Label3, 18);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "°C");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bottom_Row = lv_obj_create(ui_Bottom_Container);
    lv_obj_remove_style_all(ui_Bottom_Row);
    lv_obj_set_width(ui_Bottom_Row, 132);
    lv_obj_set_height(ui_Bottom_Row, 24);
    lv_obj_set_x(ui_Bottom_Row, 124);
    lv_obj_set_y(ui_Bottom_Row, 65);
    lv_obj_set_align(ui_Bottom_Row, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Bottom_Row, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Bottom_Row, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Bottom_Row, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Timer_Label = lv_label_create(ui_Bottom_Row);
    lv_obj_set_width(ui_Timer_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Timer_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Timer_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Timer_Label, "TOT:");
    lv_obj_set_style_text_font(ui_Timer_Label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Timer = lv_label_create(ui_Bottom_Row);
    lv_obj_set_width(ui_Timer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Timer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Timer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Timer, "00:00:00");
    lv_obj_set_style_text_font(ui_Timer, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

}
