// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ESP32TPMS

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Red[1] = {0xBB2828};
const ui_theme_variable_t _ui_theme_alpha_Red[1] = {255};

const ui_theme_variable_t _ui_theme_color_Blue[1] = {0x2828BB};
const ui_theme_variable_t _ui_theme_alpha_Blue[1] = {255};

const ui_theme_variable_t _ui_theme_color_Green[1] = {0x28BB28};
const ui_theme_variable_t _ui_theme_alpha_Green[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

